---
title: "Devoir3_Mouhamet_Seck_ISEP2"
author: "Mouhamet Seck"
date: "2025-05-04"
output: html_document
---

# Curriculum Vitae

## Informations personnelles

**Nom :** Mouhamet Seck\
**Nationalité :** Sénégalaise\
**Adresse :** Niarry Tally, Dakar, Sénégal\
**Téléphone :** (+221) 77 456 87 35\
**Email :** [seckmohamed25\@gmail.com](mailto:seckmohamed25@gmail.com){.email}

## Objectif

Étudiant en 2ème année préparatoire d'Ingénierie Statistique et Économique à l'ENSAE Dakar, je recherche un stage dans le domaine de l'analyse de données pour appliquer mes compétences en statistique.

## Formation

-   **2024-2025 :** Deuxième année préparatoire d'Ingénieur Statisticien Économiste\
    *École Nationale de la Statistique et de l'Analyse Économique (ENSAE), Dakar*

-   **2023-2024 :** Première année préparatoire d'Ingénieur Statisticien Économiste\
    *ENSAE, Dakar*

-   **2022-2023 :** Baccalauréat Série Scientifique (S1)\
    *Lycée Seydida Limamou Laye, Guédiawaye*

## Compétences

-   **Techniques :**
    -   Analyse statistique univariée/bivariée
    -   Visualisation de données (Excel, Python)
-   **Informatique :**
    -   Logiciels : SPSS, STATA, QGIS
    -   Programmation : Python, VBA
-   **Langues :**
    -   Français (langue maternelle)
    -   Anglais (intermédiaire)

## Centres d'intérêt

-   Lecture (littérature, biographies)
-   Sport (pratique régulière)

# Lettre de motivation

**À l'attention de Monsieur/Madame le Directeur**\
Afristat\
Mali, Bamako\
Dakar, le 02/05/2025

**Objet :** Candidature pour un stage en analyse statistique

Madame, Monsieur,

Actuellement en deuxième année de formation d'Ingénieur Statisticien Économiste à l'ENSAE Dakar, je me permets de vous proposer ma candidature pour un stage de deux mois au sein de votre structure. Ce stage, prévu du 01/07/2025 au 01/09/2025, s'inscrit dans le cadre de ma formation et me permettrait de perfectionner mes compétences en analyse de données.

Votre agence, reconnue pour son expertise en analyse de données, représente pour moi l'opportunité idéale d'appliquer mes connaissances en statistique, tout en contribuant à vos projets d'envergure.Doté d'une solide formation en outils statistiques, je saurai apporter rigueur analytique et créativité dans le traitement des données.

Motivé par les défis techniques et convaincu que ce stage serait mutuellement bénéfique, je reste à votre disposition pour un entretien afin de vous exposer plus en détail comment mes compétences pourraient servir vos objectifs.

Dans l'attente de votre retour, je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées.

**Signature**\
Mouhamet Seck\
(+221) 77 456 87 35\
[seckmouhamet125\@gmail.com](mailto:seckmouhamet125@gmail.com){.email}
